Group.create!(:title=>'admin')
Group.create!(:title=>'manage')
Group.create!(:title=>'user')
Group.create!(:title=>'viewer')

User.create!(:group_id=>1,:email => 'toughjjh@gmail.com', :nickname=>'잠자는-사자', :password => 'jjh123456', :password_confirmation => 'jjh123456',:photo=>File.open(Rails.root.join("app", "assets", "images", "intro", "sl.jpg")))

AdPosition.create!(:id=>1,:title=>'광고 표시안함',:position=>'none')
AdPosition.create!(:id=>2,:title=>'위에 표시',:position=>'top')
AdPosition.create!(:id=>3,:title=>'아래에 표시',:position=>'bottom')

SettingController.create!(:id=>1,:ad_position_id=>3,:title=>'메인',:menu_display=>false,:controller=>'home',:description=>'처음화면',:priority=>9000)
SettingController.create!(:id=>2,:ad_position_id=>3,:title=>'소개',:menu_display=>true,:controller=>'intro',:description=>'소개',:priority=>1000)
SettingController.create!(:id=>3,:ad_position_id=>2,:title=>'갤러리',:menu_display=>true,:controller=>'galleries',:use_category=>true,:description=>'갤러리',:priority=>2000)
SettingController.create!(:id=>4,:ad_position_id=>2,:title=>'블로그',:menu_display=>true,:controller=>'blogs',:use_category=>true,:description=>'블로그',:priority=>3000)
SettingController.create!(:id=>5,:ad_position_id=>2,:title=>'질문, 답변',:menu_display=>true,:controller=>'questions',:description=>'질문,답변',:priority=>4000)
SettingController.create!(:id=>6,:ad_position_id=>2,:title=>'FAQ',:menu_display=>true,:controller=>'faqs',:use_category=>true,:description=>'FAQ',:priority=>5000)
SettingController.create!(:id=>7,:ad_position_id=>2,:title=>'상담,문의',:menu_display=>false,:controller=>'contacts',:menu_action=>'new',:description=>'상담 문의를 받을수 있게 합니다.',:priority=>6000)
SettingController.create!(:id=>8,:ad_position_id=>1,:title=>'공지사항',:menu_display=>false,:controller=>'notices',:description=>'운영자가 방문자들에게 알릴 공지사항을 알릴수 있게 합니다.',:priority=>7000)
SettingController.create!(:id=>9,:ad_position_id=>2,:title=>'방명록',:menu_display=>true,:controller=>'guest_books',:description=>'방문자가 글을 쓸수 있는 방명록입니다.',:priority=>8000)
SettingController.create!(:id=>10,:ad_position_id=>2,:title=>'연혁',:menu_display=>false,:controller=>'histories',:description=>'연혁',:priority=>8000)
SettingController.create!(:id=>11,:ad_position_id=>2,:title=>'포트폴리오',:menu_display=>false,:controller=>'portfolios',:description=>'포트폴리오',:priority=>8000)
SettingController.create!(:id=>12,:ad_position_id=>2,:title=>'회원가입',:menu_display=>false,:controller=>'users',:menu_action=>'new',:description=>'사용자',:priority=>9000)
SettingController.create!(:id=>13,:ad_position_id=>2,:title=>'사이트',:menu_display=>false,:controller=>'site',:menu_action=>'new',:description=>'사이트 소개',:priority=>9000)
SettingController.create!(:id=>14,:ad_position_id=>2,:title=>'프로그래밍',:menu_display=>true,:controller=>'programs',:description=>'SL의 프로그래밍',:priority=>9000)

BlogCategory.create!(:id=>1,:user_id=>1,:blog_category_id=>nil,:title=>'잡생각',:blogs_count=>16,:blog_categories_count=>0,:leaf=>0,:enable=>1,:created_at=>'2013-12-24 18:26:41',:updated_at=>'2013-12-24 18:26:41')
BlogCategory.create!(:id=>2,:user_id=>1,:blog_category_id=>nil,:title=>'리눅스',:blogs_count=>0,:blog_categories_count=>4,:leaf=>0,:enable=>1,:created_at=>'2013-12-24 18:26:41',:updated_at=>'2013-12-24 18:26:41')
BlogCategory.create!(:id=>3,:user_id=>1,:blog_category_id=>nil,:title=>'웹개발',:blogs_count=>0,:blog_categories_count=>6,:leaf=>0,:enable=>1,:created_at=>'2013-12-24 18:26:41',:updated_at=>'2013-12-24 18:26:41')
BlogCategory.create!(:id=>4,:user_id=>1,:blog_category_id=>2,:title=>'설치',:blogs_count=>2,:blog_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2013-12-24 18:26:41',:updated_at=>'2013-12-24 18:26:41')
BlogCategory.create!(:id=>5,:user_id=>1,:blog_category_id=>2,:title=>'응용프로그램',:blogs_count=>6,:blog_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2013-12-24 18:26:41',:updated_at=>'2013-12-24 18:26:41')
BlogCategory.create!(:id=>6,:user_id=>1,:blog_category_id=>2,:title=>'기본명령어',:blogs_count=>0,:blog_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2013-12-24 18:26:41',:updated_at=>'2013-12-24 18:26:41')
BlogCategory.create!(:id=>7,:user_id=>1,:blog_category_id=>2,:title=>'서버',:blogs_count=>0,:blog_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2013-12-24 18:26:41',:updated_at=>'2013-12-24 18:26:41')
BlogCategory.create!(:id=>8,:user_id=>1,:blog_category_id=>3,:title=>'html',:blogs_count=>3,:blog_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2013-12-24 18:26:41',:updated_at=>'2013-12-24 18:26:41')
BlogCategory.create!(:id=>9,:user_id=>1,:blog_category_id=>3,:title=>'CSS',:blogs_count=>1,:blog_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2013-12-24 18:26:41',:updated_at=>'2013-12-24 18:26:41')
BlogCategory.create!(:id=>10,:user_id=>1,:blog_category_id=>3,:title=>'javascript',:blogs_count=>2,:blog_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2013-12-24 18:26:41',:updated_at=>'2013-12-24 18:26:41')
BlogCategory.create!(:id=>11,:user_id=>1,:blog_category_id=>3,:title=>'Ruby On Rails',:blogs_count=>5,:blog_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2014-04-14 00:00:00',:updated_at=>'2014-04-14 00:00:00')
BlogCategory.create!(:id=>12,:user_id=>1,:blog_category_id=>3,:title=>'CakePHP',:blogs_count=>3,:blog_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2014-05-18 00:00:00',:updated_at=>'2014-05-18 00:00:00')
BlogCategory.create!(:id=>13,:user_id=>1,:blog_category_id=>3,:title=>'웹개발 Tip(삽질방지)',:blogs_count=>9,:blog_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2014-05-24 00:00:00',:updated_at=>'2014-05-24 00:00:00')
BlogCategory.create!(:id=>14,:user_id=>1,:blog_category_id=>nil,:title=>'헬조선',:blogs_count=>15,:blog_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2016-01-10 15:31:45',:updated_at=>'2016-01-10 15:31:45')

GalleryCategory.create!(:id=>1,:user_id=>1,:gallery_category_id=>nil,:title=>'일상',:galleries_count=>2,:gallery_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2013-12-24 18:26:42',:updated_at=>'2013-12-24 18:26:42')
GalleryCategory.create!(:id=>2,:user_id=>1,:gallery_category_id=>nil,:title=>'멍멍이',:galleries_count=>12,:gallery_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2013-12-24 18:26:42',:updated_at=>'2013-12-24 18:26:42')
GalleryCategory.create!(:id=>3,:user_id=>1,:gallery_category_id=>nil,:title=>'가족들',:galleries_count=>19,:gallery_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2013-12-24 18:26:42',:updated_at=>'2013-12-24 18:26:42')
GalleryCategory.create!(:id=>4,:user_id=>1,:gallery_category_id=>nil,:title=>'풍경',:galleries_count=>20,:gallery_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2013-12-24 18:26:42',:updated_at=>'2013-12-24 18:26:42')
GalleryCategory.create!(:id=>5,:user_id=>1,:gallery_category_id=>nil,:title=>'기타',:galleries_count=>1,:gallery_categories_count=>0,:leaf=>1,:enable=>1,:created_at=>'2013-12-24 18:26:42',:updated_at=>'2013-12-24 18:26:42')


ProgramLanguage.create!(:id=>1,:title=>'ruby',:link=>'http://www.php.net/',:enable=>1)
ProgramLanguage.create!(:id=>2,:title=>'PHP',:link=>'https://www.ruby-lang.org/',:enable=>1)
ProgramLanguage.create!(:id=>3,:title=>'CSS',:link=>nil,:enable=>1)
ProgramLanguage.create!(:id=>4,:title=>'javascript',:link=>nil,:enable=>1)
ProgramLanguage.create!(:id=>5,:title=>'java',:link=>'https://www.java.com/',:enable=>1)
ProgramLanguage.create!(:id=>6,:title=>'python',:link=>'https://www.python.org/',:enable=>1)

ProgramCategory.create!(:id=>1,:program_language_id=>1,:title=>'Ruby on Rails',:link=>'http://rubyonrails.org/',:enable=>1)
ProgramCategory.create!(:id=>2,:program_language_id=>2,:title=>'Pure PHP',:link=>nil,:enable=>1)
ProgramCategory.create!(:id=>3,:program_language_id=>2,:title=>'Wordpress',:link=>'https://wordpress.org/',:enable=>1)
ProgramCategory.create!(:id=>4,:program_language_id=>2,:title=>'Mediawiki',:link=>'https://www.mediawiki.org/wiki/MediaWiki',:enable=>1)
ProgramCategory.create!(:id=>5,:program_language_id=>2,:title=>'Codeigniter',:link=>'https://codeigniter.com/',:enable=>1)
ProgramCategory.create!(:id=>6,:program_language_id=>2,:title=>'CakePHP',:link=>'https://cakephp.org/',:enable=>1)

ProgramCategory.create!(:id=>7,:program_language_id=>3,:title=>'Boostrap',:link=>'http://getbootstrap.com/',:enable=>1)
ProgramCategory.create!(:id=>8,:program_language_id=>4,:title=>'Jquery',:link=>'https://jquery.com/',:enable=>1)

Program.create!(:id=>1,:title=>'잠자는사자의 집(ROR)',:description=>'',:service_link=>'http://www.sleepinglion.pe.kr',:use_database=>true,:enable=>true)
Program.create!(:id=>2,:title=>'잠자는사지의 집(codeigniter)',:description=>'',:service_link=>'',:use_database=>true,:enable=>true)
Program.create!(:id=>3,:title=>'안티 살인은행',:description=>'',:service_link=>'http://www.antikb.site',:use_database=>true,:enable=>true)
Program.create!(:id=>4,:title=>'SL FTP',:description=>'',:service_link=>'http://www.sl-ftp.site',:use_database=>false,:enable=>true)
Program.create!(:id=>5,:title=>'모바일웹 플랫폼(ROR)',:description=>'',:use_database=>true,:enable=>true)
Program.create!(:id=>6,:title=>'모바일웹 플랫폼(codeigniter)',:description=>'',:use_database=>true,:enable=>true)
Program.create!(:id=>7,:title=>'관련링크관리 플러그인',:description=>'',:service_link=>'https://www.mediawiki.org/wiki/Extension:RelatedLinks',:use_database=>true,:enable=>true)
Program.create!(:id=>8,:title=>'로고관리 플러그인',:description=>'',:service_link=>'https://www.mediawiki.org/wiki/Extension:UploadLogo',:use_database=>false,:enable=>true)

ProgramCategoriesProgram.create!(:program_category_id=>1,:program_id=>1,:main=>true)
ProgramCategoriesProgram.create!(:program_category_id=>5,:program_id=>2,:main=>true)
ProgramCategoriesProgram.create!(:program_category_id=>1,:program_id=>3,:main=>true)
ProgramCategoriesProgram.create!(:program_category_id=>2,:program_id=>4,:main=>true)
ProgramCategoriesProgram.create!(:program_category_id=>1,:program_id=>5,:main=>true)
ProgramCategoriesProgram.create!(:program_category_id=>2,:program_id=>6,:main=>true)
ProgramCategoriesProgram.create!(:program_category_id=>4,:program_id=>7,:main=>true)
ProgramCategoriesProgram.create!(:program_category_id=>4,:program_id=>8,:main=>true)

ProgramCategoriesProgram.create!(:program_category_id=>7,:program_id=>1,:main=>false)
ProgramCategoriesProgram.create!(:program_category_id=>8,:program_id=>1,:main=>false)
ProgramCategoriesProgram.create!(:program_category_id=>7,:program_id=>2,:main=>false)
ProgramCategoriesProgram.create!(:program_category_id=>8,:program_id=>2,:main=>false)
ProgramCategoriesProgram.create!(:program_category_id=>7,:program_id=>3,:main=>false)
ProgramCategoriesProgram.create!(:program_category_id=>8,:program_id=>3,:main=>false)
ProgramCategoriesProgram.create!(:program_category_id=>7,:program_id=>4,:main=>false)
ProgramCategoriesProgram.create!(:program_category_id=>8,:program_id=>4,:main=>false)
